version: "3.1"

services:
    client:
        build: ./src/client
        container_name: client-pogtracker
        ports:
            - "3000:3000"
        volumes:
            - ./src/client:/usr/src/app
            - /usr/src/app/node_modules/
        networks:
            - frontend-pogtracker-network
    server:
        build: ./src/server
        container_name: server-pogtracker
        volumes:
            - ./src/server:/usr/src/app
            - /usr/src/app/node_modules/
        networks:
            - frontend-pogtracker-network
networks:
    frontend-pogtracker-network:
        driver: bridge

#services:
#    client:
#        build: ./src/client
#        container_name: client-pogtracker
#        ports:
#            - "3000:3000"
#        volumes:
#            - ./src/client:/usr/src/app
#            - /usr/src/app/node_modules/
#        networks:
#            - frontend-pogtracker-network
#    server:
#        build: ./src/server
#        container_name: server-pogtracker
#        volumes:
#            - ./src/server:/usr/src/app
#        networks:
#            - frontend-pogtracker-network
#            - backend-pogtracker-network
#    mongodb:
#        image: mongo
#        container_name: database-pogtracker
#        volumes:
#            - ./src/data/db:/data/db
#        networks:
#            - backend-pogtracker-network
#networks:
#    frontend-pogtracker-network:
#        driver: bridge
#    backend-pogtracker-network:
#        driver: bridge
